<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="6" passed="5">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="8731" started-at="2021-10-09T13:41:47Z" finished-at="2021-10-09T13:41:56Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="8731" started-at="2021-10-09T13:41:47Z" finished-at="2021-10-09T13:41:56Z">
      <class name="web_drive.Topic_03_Xpath_Css">
        <test-method status="PASS" signature="beforeClass()[pri:0, instance:web_drive.Topic_03_Xpath_Css@1081592]" name="beforeClass" is-config="true" duration-ms="2089" started-at="2021-10-09T13:41:47Z" finished-at="2021-10-09T13:41:49Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeClass -->
        <test-method status="PASS" signature="TC_01_ValidateCurrentUrl()[pri:0, instance:web_drive.Topic_03_Xpath_Css@1081592]" name="TC_01_ValidateCurrentUrl" duration-ms="3121" started-at="2021-10-09T13:41:49Z" finished-at="2021-10-09T13:41:52Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_01_ValidateCurrentUrl -->
        <test-method status="PASS" signature="TC_02_Regis_with_invalid_email()[pri:0, instance:web_drive.Topic_03_Xpath_Css@1081592]" name="TC_02_Regis_with_invalid_email" duration-ms="638" started-at="2021-10-09T13:41:52Z" finished-at="2021-10-09T13:41:53Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_02_Regis_with_invalid_email -->
        <test-method status="PASS" signature="TC_03_Regis_with_invalid_Cemail()[pri:0, instance:web_drive.Topic_03_Xpath_Css@1081592]" name="TC_03_Regis_with_invalid_Cemail" duration-ms="619" started-at="2021-10-09T13:41:53Z" finished-at="2021-10-09T13:41:53Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_03_Regis_with_invalid_Cemail -->
        <test-method status="PASS" signature="TC_04_Regis_with_invalid_pass()[pri:0, instance:web_drive.Topic_03_Xpath_Css@1081592]" name="TC_04_Regis_with_invalid_pass" duration-ms="574" started-at="2021-10-09T13:41:53Z" finished-at="2021-10-09T13:41:54Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_04_Regis_with_invalid_pass -->
        <test-method status="PASS" signature="TC_05_Regis_with_invalid_Cpass()[pri:0, instance:web_drive.Topic_03_Xpath_Css@1081592]" name="TC_05_Regis_with_invalid_Cpass" duration-ms="468" started-at="2021-10-09T13:41:54Z" finished-at="2021-10-09T13:41:54Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_05_Regis_with_invalid_Cpass -->
        <test-method status="FAIL" signature="TC_05_Regis_with_invalid_phone()[pri:0, instance:web_drive.Topic_03_Xpath_Css@1081592]" name="TC_05_Regis_with_invalid_phone" duration-ms="779" started-at="2021-10-09T13:41:54Z" finished-at="2021-10-09T13:41:55Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Số điện thoại phải từ 10-11 số.] but found [Vui lòng nhập con số]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Số điện thoại phải từ 10-11 số.] but found [Vui lòng nhập con số]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at web_drive.Topic_03_Xpath_Css.TC_05_Regis_with_invalid_phone(Topic_03_Xpath_Css.java:112)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_05_Regis_with_invalid_phone -->
        <test-method status="PASS" signature="afterClass()[pri:0, instance:web_drive.Topic_03_Xpath_Css@1081592]" name="afterClass" is-config="true" duration-ms="423" started-at="2021-10-09T13:41:55Z" finished-at="2021-10-09T13:41:56Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterClass -->
      </class> <!-- web_drive.Topic_03_Xpath_Css -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
